### ISSUE TITLE
Suggestions for README updates

### ISSUE THREAD

**Issue by pulkitsinghal** [GovRight/loopback-console#1]
You can find the content that I think might make the README more appealing here:
https://github.com/GovRight/loopback-console/wiki/README-edits-by-Pulkit

Also theres is some additional content here, use as you see fit:
https://github.com/GovRight/loopback-console/wiki/FAQs-by-Pulkit

**Comment by doublemarked** [comment]
I've overhauled the README. Let me know what you think? I have not yet linked to the FAQ, but I would like to after updating it a bit.
