### ISSUE TITLE
Need more examples 

### ISSUE THREAD

**Issue by pulkitsinghal** [GovRight/loopback-console#2]
1. Consider adding an `example` directory inside `loopback-console` which was ignored for publishing with `.npmignore` but used by those who clone this project to quickly experiment a slew of HOW-TOs on usage for loopback-console
2. Add lots of command-line examples to show people how they can make the most of this tool

**Comment by doublemarked** [comment]
FYI - I've now included a video demonstrating its use and a text snippet of example usage.
