### ISSUE TITLE
add a help command to the REPL

### ISSUE THREAD

**Issue by pulkitsinghal** [GovRight/loopback-console#3]
```
$ loopback-console .
...
loopback > help
ReferenceError: help is not defined
loopback > models
ReferenceError: models is not defined
```

There should be a way to see the `help` again which right now only pops-up in the beginning and then gets lost as the screen scrolls up ... and probably something called `models` also, it helps when someone _only_ wants all the existing models listed.

**Comment by doublemarked** [comment]
I've added two new REPL keywords, 
- `.usage`: reprints the opening text
- `.models`: lists available models
