### ISSUE TITLE
Reload codebase from within console instance

### ISSUE THREAD

**Issue by gausie** [GovRight/loopback-console#4]
Would be great to be able to keep all the variables that have been set but reload the code in place.

**Comment by doublemarked** [comment]
Hey Samuel - this is a good suggestion, and we'll see if we can get it included.

**Comment by doublemarked** [comment]
Hey @gausie - spent some time thinking about this but have come to feel that such a reload (while maintaining console state) is probably unrealistic. It would be difficult to ensure that local variables that point to model instances (and other LB components) got reloaded with the new code. It's possible to do in a poor way but complex to do comprehensively. Sorry about this!
